[workspace]
authors = ["Alvaro Gaona <alvgaona@gmail.com>"]
channels = ["conda-forge", "robostack-humble"]
name = "lidar"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
clean = "rm -rf build/ install/ log/"
build-pkg = "sh -c 'colcon build --packages-up-to \"$0\" --symlink-install --event-handlers console_direct+ --cmake-args -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=\"-Wall\" -DPython3_EXECUTABLE=$(which python) -DPython_EXECUTABLE=$(which python)'"
test-pkg = "sh -c 'colcon test --packages-up-to \"$0\" --event-handlers console_direct+'"
build-livox-sdk = "cmake -B src/Livox-SDK2/build -S src/Livox-SDK2 && cmake --build src/Livox-SDK2/build && cmake --install src/Livox-SDK2/build"

[dependencies]
colcon-common-extensions = ">=0.3.0,<0.4"
cmake = ">=4.1.2,<5"
ninja = ">=1.13.1,<2"
eigen = ">=3.4.0,<4"
libboost-devel = ">=1.86.0,<2"
pcl = ">=1.15.0,<2"
libpcap = ">=1.10.4,<2"
yaml-cpp = ">=0.8.0,<0.9"

[feature.humble.dependencies]
ros-humble-desktop-full = "*"

[environments]
default = ["humble"]

[activation]
scripts = ["install/setup.bash"]
